# Generated by Django 3.2.5 on 2022-06-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SpareParts', '0001_initial'),
        ('Treasury', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachinesNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='اسم الصنف')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MachinesSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم المورد')),
                ('phone', models.CharField(max_length=11, verbose_name='رقم الهاتف')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
        migrations.CreateModel(
            name='MachinesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
            ],
        ),
        migrations.CreateModel(
            name='MachinesWarehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='اسم المخزن')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0, verbose_name='الكمية')),
                ('purchase_cost', models.FloatField(default=0.0, verbose_name='سعر الشراء')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machines.machinesnames', verbose_name='المنتج')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Machines.machineswarehouses', verbose_name='المخزن')),
            ],
        ),
        migrations.CreateModel(
            name='MachinesOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, null=True, verbose_name='رقم الطلب')),
                ('order_date', models.DateField(null=True, verbose_name='تاريخ الطلب')),
                ('order_deposit_value', models.FloatField(default=0, null=True, verbose_name='قيمة العربون')),
                ('order_deposit_date', models.DateField(null=True, verbose_name='تاريخ دفع العربون')),
                ('order_rest_date', models.DateField(null=True, verbose_name='تاريخ دفع باقي المبلغ')),
                ('order_receipt_date', models.DateField(null=True, verbose_name='تاريخ استلام البضاعة')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('order_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Machines.machinessuppliers', verbose_name='المورد')),
            ],
        ),
        migrations.CreateModel(
            name='MachinesOrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField(default=0, null=True, verbose_name='الكمية')),
                ('product_price', models.FloatField(default=0, null=True, verbose_name='سعر الشراء')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Machines.machinesnames', verbose_name='المنتج')),
                ('product_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Machines.machinesorders', verbose_name='الطلبية')),
            ],
        ),
        migrations.CreateModel(
            name='MachinesOrderOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateTimeField(null=True, verbose_name='تاريخ العملية')),
                ('operation_type', models.IntegerField(choices=[(1, 'دفع عربون'), (2, 'دفع باقي المبلغ'), (3, 'دفع مبلغ تخليص البضاعة'), (4, 'استلام البضاعة'), (5, 'دفع الضرائب')], default=0, verbose_name='نوع العملية')),
                ('operation_value', models.FloatField(default=0, verbose_name='قيمة العملية')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machines.machinesorders', verbose_name='رقم الطلب')),
                ('treasury_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Treasury.worktreasury', verbose_name='الخزنة المستخدمة')),
                ('warehouse_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Machines.machineswarehouses', verbose_name='المخزن المستخدم')),
            ],
        ),
        migrations.AddField(
            model_name='machinesnames',
            name='machine_type',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='Machines.machinestypes', verbose_name='نوع المكينة'),
        ),
        migrations.CreateModel(
            name='MachineNotifecation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True, verbose_name='تاريخ الانشاء')),
                ('notifeaction_type', models.IntegerField(choices=[(1, 'موعد دفع عربون مكينة'), (2, 'موعد دفع باقي مبلغ مكينة'), (3, 'موعد استلام بضاعة مكينة'), (4, 'موعد دفع ضرائب مكينة'), (5, 'موعد دفع عربون قطع غيار'), (6, 'موعد دفع باقي مبلغ قطع غيار'), (7, 'موعد استلام بضاعة قطع غيار'), (8, 'موعد ضرائب قطع غيار')], default=0, verbose_name='نوع الاشعار')),
                ('message', models.CharField(max_length=100, null=True, verbose_name=' الرسالة')),
                ('read', models.BooleanField(default=0, verbose_name='قرأت / لم تقرأ')),
                ('machine_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Machines.machinesorders', verbose_name='طلبية المكن')),
                ('spare_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SpareParts.sparepartsorders', verbose_name='طلبية قطع الغيار')),
            ],
        ),
    ]
