# Generated by Django 3.2.5 on 2022-06-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_active', models.BooleanField(default=True, verbose_name='تنشيط المكينات')),
                ('spareParts_active', models.BooleanField(default=True, verbose_name='تنشيط قطع الغيار')),
                ('treasurty_active', models.BooleanField(default=True, verbose_name='تنشيط الخزينة')),
                ('factory_active', models.BooleanField(default=True, verbose_name='تنشيط المصانع')),
                ('products_active', models.BooleanField(default=True, verbose_name='تنشيط المنتجات')),
                ('wools_active', models.BooleanField(default=True, verbose_name='تنشيط مخازن الصوف ')),
                ('worker_active', models.BooleanField(default=True, verbose_name='تنشيط مخازن العمال ')),
            ],
        ),
        migrations.CreateModel(
            name='SystemInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='اسم النظام')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='نوع النظام')),
                ('manage', models.CharField(max_length=50, null=True, verbose_name='إدارة')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='هاتف 1')),
                ('phone2', models.CharField(max_length=11, null=True, verbose_name='هاتف 2')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='العنوان')),
            ],
        ),
    ]
