# Generated by Django 3.2.5 on 2022-06-01 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WoolColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='لون الصوف')),
            ],
        ),
        migrations.CreateModel(
            name='WoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الخامة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اضيف بواسطة')),
            ],
        ),
        migrations.CreateModel(
            name='Wool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name=' الصوف')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('cost', models.IntegerField(verbose_name='سعر الشراء')),
                ('price', models.IntegerField(verbose_name='سعر البيع')),
                ('wool_color', models.ManyToManyField(blank=True, null=True, to='Wool.WoolColor')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الشركة')),
                ('phone', models.CharField(max_length=15, verbose_name='موبيل الشركة')),
                ('address', models.CharField(max_length=50, verbose_name='عنوان الشركة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة الشركة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اضيف بواسطة')),
            ],
        ),
    ]
