# Generated by Django 3.2.5 on 2022-04-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoolColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='لون الصوف')),
            ],
        ),
        migrations.RemoveField(
            model_name='wool',
            name='color',
        ),
        migrations.AddField(
            model_name='wool',
            name='wool_color',
            field=models.ManyToManyField(to='Wool.WoolColor'),
        ),
    ]
