# Generated by Django 3.2.5 on 2022-04-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0003_auto_20220419_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='wool',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name=' الصوف'),
            preserve_default=False,
        ),
    ]
