# Generated by Django 3.2.5 on 2022-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0004_wool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wool',
            name='wool_color',
            field=models.ManyToManyField(blank=True, null=True, to='Wool.WoolColor'),
        ),
    ]
