# Generated by Django 3.2.5 on 2022-06-12 00:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المصنع')),
                ('hour_price', models.FloatField(blank=True, null=True, verbose_name='حساب الساعه')),
                ('machine_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المكن')),
                ('machine_count', models.IntegerField(blank=True, null=True, verbose_name='عدد المكن')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الهاتف')),
                ('active', models.BooleanField(default=True, verbose_name='يعمل')),
                ('start_date', models.DateField(default=datetime.date.today, null=True, verbose_name='تاريخ البداية')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('price', models.FloatField(verbose_name='المبلغ')),
                ('recipient', models.CharField(max_length=50, verbose_name='المستلم')),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Factories.factory', verbose_name='المصنع')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryOutSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='الوزن بالكيلو')),
                ('wool_type', models.IntegerField(blank=True, choices=[(1, 'قطن'), (2, 'صوف'), (3, 'عجينة'), (4, 'سبن'), (5, 'لكرة'), (6, 'رمش'), (7, 'عصب'), (8, 'بلستر'), (9, 'استك')], null=True, verbose_name='نوع الخامة')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون')),
                ('percent_loss', models.FloatField(blank=True, null=True, verbose_name='الهالك (نسبة مؤية)')),
                ('weight_after_loss', models.FloatField(blank=True, null=True, verbose_name='الوزن بعد الهالك')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Factories.factory', verbose_name='المصنع')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryInSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='الوزن بالكيلو')),
                ('product_weight', models.FloatField(blank=True, null=True, verbose_name='وزن الموديل جرام')),
                ('product_time', models.FloatField(blank=True, null=True, verbose_name='زمن الموديل دقائق')),
                ('product_count', models.FloatField(blank=True, null=True, verbose_name='عدد الموديل')),
                ('wool_type', models.IntegerField(blank=True, choices=[(1, 'قطن'), (2, 'صوف'), (3, 'عجينة'), (4, 'سبن'), (5, 'لكرة'), (6, 'رمش'), (7, 'عصب'), (8, 'بلستر'), (9, 'استك')], null=True, verbose_name='نوع الخامة')),
                ('hour_count', models.FloatField(blank=True, null=True, verbose_name='عدد الساعات')),
                ('hour_price', models.FloatField(blank=True, null=True, verbose_name='سعر الساعة')),
                ('total_account', models.FloatField(blank=True, null=True, verbose_name='اجمالي الحساب')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Factories.factory', verbose_name='المصنع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='الموديل')),
            ],
        ),
    ]
