# Generated by Django 3.2.5 on 2022-04-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0003_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerattendance',
            name='hour_count',
            field=models.IntegerField(choices=[(1, '6'), (2, '8'), (3, '12'), (4, '18')], verbose_name='عدد الساعات'),
        ),
    ]
