# Generated by Django 3.2.5 on 2022-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0004_alter_workerattendance_hour_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.IntegerField(choices=[(1, 'عامل ارضية'), (2, 'عامل خياطة'), (3, 'عامل مكوي'), (4, 'عامل مكينة'), (5, 'عامل عادي'), (6, 'عامل انتاج')], verbose_name='نوع العامل'),
        ),
    ]
