# Generated by Django 3.2.5 on 2022-06-03 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0004_auto_20220603_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 3, 12, 55, 52, 148348, tzinfo=utc), verbose_name='تاريخ الحضور'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 3, 12, 55, 52, 149355, tzinfo=utc), verbose_name='تاريخ السحب'),
        ),
        migrations.AlterField(
            model_name='workerproduction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 3, 12, 55, 52, 149355, tzinfo=utc), verbose_name='تاريخ الاستلام'),
        ),
    ]
