# Generated by Django 3.2.5 on 2022-05-14 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0005_auto_20220514_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerproduction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 13, 1, 48, 406559, tzinfo=utc), verbose_name='تاريخ الاستلام'),
        ),
    ]
