# Generated by Django 3.2.5 on 2022-05-18 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0006_alter_workerproduction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerproduction',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='workerattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 19, 6, 22, 574692, tzinfo=utc), verbose_name='تاريخ الحضور'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 19, 6, 22, 574692, tzinfo=utc), verbose_name='تاريخ السحب'),
        ),
        migrations.AlterField(
            model_name='workerproduction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 19, 6, 22, 574692, tzinfo=utc), verbose_name='تاريخ الاستلام'),
        ),
    ]
