# Generated by Django 3.2.5 on 2022-05-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0005_alter_worker_worker_type'),
        ('Workers', '0007_auto_20220518_2106'),
    ]

    operations = [
    ]
