# Generated by Django 3.2.5 on 2022-05-28 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0009_auto_20220523_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 28, 15, 15, 0, 901214, tzinfo=utc), verbose_name='تاريخ الحضور'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 28, 15, 15, 0, 901214, tzinfo=utc), verbose_name='تاريخ السحب'),
        ),
        migrations.AlterField(
            model_name='workerproduction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 28, 15, 15, 0, 901214, tzinfo=utc), verbose_name='تاريخ الاستلام'),
        ),
    ]
