# Generated by Django 3.2.5 on 2022-06-01 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم اللون')),
                ('code', models.CharField(max_length=20, verbose_name='كود اللون')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم التاجر')),
                ('phone', models.CharField(max_length=11, verbose_name='رقم الهاتف')),
                ('initial_balance_debit', models.FloatField(default=0, verbose_name='القيمة الافتتاحية')),
                ('initial_balance_type', models.IntegerField(choices=[(1, 'للتاجر'), (2, 'علي التاجر')], default=0, verbose_name='نوع القيمة الافتتاحية')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
        migrations.CreateModel(
            name='SellerPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_value', models.FloatField(default=0.0, verbose_name='القيمة المدفوعة')),
                ('paid_type', models.IntegerField(choices=[(1, 'التاجر يدفع لك'), (2, 'أنت تدفع للتاجر')], default=0, verbose_name='نوع الدفع')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 6, 1, 21, 36, 46, 828256), verbose_name='التاريخ')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsellers', verbose_name='التاجر')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الموديل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة الموديل')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='وزن الموديل')),
                ('cost', models.FloatField(blank=True, max_length=15, null=True, verbose_name='التكلفة')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='سعر البيع')),
                ('size', models.IntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (3, 'XL'), (3, 'XXL')], default=0, verbose_name='المقاس')),
                ('category', models.IntegerField(choices=[(1, 'شبابي'), (2, 'حريمي'), (3, 'اولادي')], default=0, verbose_name='التصنيف')),
                ('quantity', models.IntegerField(null=True, verbose_name='الكمية')),
                ('deleted', models.BooleanField(default=False)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.color', verbose_name='اللون')),
            ],
        ),
    ]
