# Generated by Django 3.2.5 on 2022-06-03 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 14, 45, 13, 141281), verbose_name='التاريخ'),
        ),
    ]
