# Generated by Django 3.2.5 on 2022-06-03 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 14, 54, 36, 151801), verbose_name='التاريخ'),
        ),
    ]
