# Generated by Django 3.2.5 on 2022-06-04 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 19, 18, 20213), verbose_name='التاريخ'),
        ),
    ]
