# Generated by Django 3.2.5 on 2022-04-19 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20220308_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 2, 10, 9, 326330), verbose_name='التاريخ'),
        ),
    ]
