# Generated by Django 3.2.5 on 2022-06-04 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 20, 37, 14, 592448), verbose_name='التاريخ'),
        ),
    ]
