# Generated by Django 3.2.5 on 2022-04-19 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 2, 17, 10, 712683), verbose_name='التاريخ'),
        ),
    ]
