# Generated by Django 3.2.5 on 2022-05-15 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 18, 18, 38, 486793), verbose_name='التاريخ'),
        ),
    ]
