# Generated by Django 3.2.5 on 2022-05-19 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsellers',
            name='initial_balance_type',
            field=models.IntegerField(choices=[(1, 'للتاجر'), (2, 'علي التاجر')], default=0, verbose_name='نوع القيمة'),
        ),
        migrations.AlterField(
            model_name='productsellers',
            name='initial_balance_debit',
            field=models.FloatField(default=0, verbose_name='القيمة الافتتاحية'),
        ),
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 21, 11, 5, 298357), verbose_name='التاريخ'),
        ),
    ]
