# Generated by Django 3.2.5 on 2022-05-19 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_auto_20220519_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsellers',
            name='initial_balance_type',
            field=models.IntegerField(choices=[(1, 'للتاجر'), (2, 'علي التاجر')], default=0, verbose_name='نوع القيمة الافتتاحية'),
        ),
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 21, 14, 2, 446339), verbose_name='التاريخ'),
        ),
    ]
