# Generated by Django 3.2.5 on 2022-05-19 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_auto_20220519_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpayments',
            name='paid_type',
            field=models.IntegerField(choices=[(1, 'التاجر يدفع لك'), (2, 'أنت تدفع للتاجر')], default=0, verbose_name='نوع الدفع'),
        ),
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 21, 34, 28, 701089), verbose_name='التاريخ'),
        ),
    ]
