# Generated by Django 3.2.5 on 2022-05-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_alter_sellerpayments_date'),
        ('Products', '0014_auto_20220519_2134'),
    ]

    operations = [
    ]
