# Generated by Django 3.2.5 on 2022-05-23 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_merge_20220523_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 14, 53, 20, 928399), verbose_name='التاريخ'),
        ),
    ]
