# Generated by Django 3.2.5 on 2022-05-28 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 17, 15, 0, 896743), verbose_name='التاريخ'),
        ),
    ]
